### ISSUE TITLE
3.0.0+ prevents LLDB from working

### ISSUE THREAD

**Issue by apoltix** [twilio/conversations-ios#36] opened 2023-05-05 10:11 UTC
Hi,

I updated our project to use the newly released v3.1.0 (the issue also happens with 3.0.0, but not previous 2.x.x versions), integrated using SPM. Any and all debugging using the LLDB console causes the following output:

```
(lldb) po 1
error: expression failed to parse:
error: virtual filesystem overlay file '/Users/distiller/rtd-sdk-monorepo/sdk/ios/Local/temp/DerivedData/Build/Intermediates.noindex/ArchiveIntermediates/TwilioConversationsClient/IntermediateBuildFilesPath/TwilioConversationsClient.build/Release-iphonesimulator/TwilioConversationsClient.build/all-product-headers.yaml' not found
error: virtual filesystem overlay file '/Users/distiller/rtd-sdk-monorepo/sdk/ios/Local/temp/DerivedData/Build/Intermediates.noindex/ArchiveIntermediates/TwilioConversationsClient/IntermediateBuildFilesPath/TwilioConversationsClient.build/Release-iphonesimulator/TwilioConversationsClient.build/all-product-headers.yaml' not found

error: couldn't IRGen expression. Please check the above error messages for possible root causes.
```

This is an old and [classic issue](https://steipete.com/posts/couldnt-irgen-expression/) that seems to happen when building distributed Swift frameworks (seemingly when using Carthage or even directly with `xcodebuild`).  There are a few [guides](https://medium.com/strava-engineering/how-to-fix-lldb-couldnt-irgen-expression-when-using-carthage-b0a111e02497) out there to avoid this.

The issue can be reproduced by creating a new iOS app project, add the Twilio `conversations-ios` dependency via SPM, setting a breakpoint in e.g. `application(_:didFinishLaunchingWithOptions:)` and running the project with no code modifications. When the breakpoint is hit, try anything in the debugger console, even `po 1`, and it will fail with the error above.

As a workaround, anecdotally I can get debugging to work again by copying the `all-product-headers.yaml` file from another target's `DerivedData` folder to this location:

```json
{"case-sensitive":"false","roots":[],"version":0}
```

Would it be possible to attempt following the guides so this issue can be avoided? Let me know if you need further information.

Thanks,
Christian

**Comment by Gray-Wind** [comment] 2023-05-05 10:13
Thank you for reaching out, I will take a look at this issue ASAP.

**Comment by Gray-Wind** [comment] 2023-05-08 11:33
Hey @apoltix,

I have a hard time trying to reproduce the issue, It would be very helpful if you'll be able to make a minimum reproduction project, so I'll be able to check a fix for the problem.

**Comment by apoltix** [comment] 2023-05-09 13:46
@Gray-Wind Thanks for checking. It does appear the issue doesn't occur when using Xcode 14.3, only 14.2.

In that case, it might be fine to close this unless enough users are on 14.2.

**Comment by Gray-Wind** [comment] 2023-05-09 14:01
Hey @apoltix,

Thank you for letting me know! Since there is a known way to make it work, I will close it for now. We may take another look into the issue when (if) more people will complain.

**Closed by Gray-Wind** 2023-05-09 14:01 UTC
Labels: bug

**Comment by mthormann-dhi** [comment] 2023-07-17 20:11
I can confirm it happens in Xcode 14.3.1 but with Twilio 4.x. Reverting to 3.1.0 fixed it
